#ifndef RATING_H
#define RATING_H

typedef enum Rating {
    LOW_RATING,
    MEDIUM_RATING,
    HIGH_RATING,
    VERY_HIGH_RATING,
    RATING_MAX_ENUM,
} Rating;

static const Rating RATINGS_ASC[RATING_MAX_ENUM] = {LOW_RATING, MEDIUM_RATING, HIGH_RATING, VERY_HIGH_RATING};
static const Rating RATINGS_DESC[RATING_MAX_ENUM] = {VERY_HIGH_RATING, HIGH_RATING, MEDIUM_RATING, LOW_RATING};

#endif
